[package]
name = "usb-timing-box-rs"
version = "0.1.0"
edition = "2024"
rust-version = "1.88.0"
publish = true
license = "MIT"
description = "Rust library for interfacing with a race result usb timing box via serial connection."
repository = "https://github.com/TimoLehnertz/usb-timing-box-rs"
readme = "README.md"
keywords = ["timing-box", "box", "race-result", "serial"]
categories = ["hardware-support"]

[package.metadata.docs.rs]
all-features = true

[features]
default = ["chrono"]
chrono = ["dep:chrono"]
serde = ["dep:serde"]
schemars = ["dep:schemars"]

[[example]]
name = "read_passings"

[dependencies]
chrono = { version = "0.4", optional = true, default-features = false, features = ["std", "clock"] }
serialport = "4.8.1"
schemars = { version = "0.9", optional = true, features = ["derive"] }
serde = { version = "1.0", optional = true, features = ["derive"] }
thiserror = "2.0.12"
